### PR TITLE
Manage Grafana Dashboard through code

### PR DESCRIPTION
**Pull request by rohit-dimagi**
* Provision Dashboard Via grafana provisioning API
* Add All the grafana dashboard as a code

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
Nice, I'm all for having this in the repo but how will we keep these in sync if we make changes to these on Grafana?

**Comment by rohit-dimagi** [comment]
> Nice, I'm all for having this in the repo but how will we keep these in sync if we make changes to these on Grafana?
If a provisioned dashboard is saved from the UI and then later updated from the source, the dashboard stored in the database will always be overwritten. So we have to put it here after updating anything on UI, Not always but maybe once per month.

**Comment by snopoke** [comment]
> So we have to put it here after updating anything on UI, Not always but maybe once per month.

It would be useful to create a script to do this. We have something like this for Datadog monitors that are kept in the repo: https://github.com/dimagi/commcare-cloud/blob/b7804115fd4aad39cb4041a3c12a6f3a7cf20acd/src/commcare_cloud/manage_commcare_cloud/datadog_monitors.py#L280

**Comment by rohit-dimagi** [comment]
Closing for now. will add it later

**Pull request closed without merging**
